-- Run this once in your Supabase project's SQL Editor (free tier is enough).
-- Mirrors the local app's `transactions`/`batches` tables (backend/app/db.py), adapted for
-- Postgres. If you already ran an earlier version of this file, it's safe to re-run - the
-- ADD COLUMN / CREATE TABLE IF NOT EXISTS statements below are no-ops on things that already
-- exist.

create table if not exists batches (
    name text primary key,
    is_favorite boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    batch_name text references batches(name) on delete set null,
    draft_slot integer not null default 1,
    sender_name text,
    transaction_date text,
    transaction_time text,
    amount numeric,
    raw_ocr_text text,
    llm_raw_response text,
    confidence numeric,
    status text not null default 'pending',
    image_url text,
    created_at timestamptz not null default now()
);

-- Safe to re-run on a database created from an older version of this file.
alter table transactions add column if not exists draft_slot integer not null default 1;

-- Enable Row Level Security and allow the anon key to do everything. This app has no
-- login/auth, so anyone with the shared link can read/write - fine for a small group of
-- friends sharing one instance, not meant for a public untrusted audience.
alter table batches enable row level security;
alter table transactions enable row level security;

drop policy if exists "anon full access" on batches;
create policy "anon full access" on batches
    for all
    to anon
    using (true)
    with check (true);

drop policy if exists "anon full access" on transactions;
create policy "anon full access" on transactions
    for all
    to anon
    using (true)
    with check (true);

-- Also create a public Storage bucket named "slip-images" from the Supabase dashboard
-- (Storage -> New bucket -> name: slip-images -> Public bucket: on). That can't be done
-- from SQL alone.
--
-- "Public bucket" only makes reading files public - it does NOT grant upload access.
-- Storage has its own RLS (on storage.objects), separate from the transactions table's
-- policy above, so it needs its own policies or every upload fails with a StorageException.
drop policy if exists "anon upload access" on storage.objects;
create policy "anon upload access"
    on storage.objects
    for insert
    to anon
    with check (bucket_id = 'slip-images');

drop policy if exists "anon read access" on storage.objects;
create policy "anon read access"
    on storage.objects
    for select
    to anon
    using (bucket_id = 'slip-images');
