-- Run this once in your Supabase project's SQL Editor (free tier is enough).
-- Mirrors the local app's `transactions` table (backend/app/db.py), adapted for Postgres
-- and with batch_name replacing the local batches table (simpler, good enough here).

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    batch_name text,
    sender_name text,
    transaction_date text,
    transaction_time text,
    amount numeric,
    raw_ocr_text text,
    llm_raw_response text,
    confidence numeric,
    status text not null default 'pending',
    image_url text,
    created_at timestamptz not null default now()
);

-- Enable Row Level Security and allow the anon key to do everything. This app has no
-- login/auth, so anyone with the shared link can read/write - fine for a small group of
-- friends sharing one instance, not meant for a public untrusted audience.
alter table transactions enable row level security;

create policy "anon full access" on transactions
    for all
    to anon
    using (true)
    with check (true);

-- Also create a public Storage bucket named "slip-images" from the Supabase dashboard
-- (Storage -> New bucket -> name: slip-images -> Public bucket: on). That can't be done
-- from SQL alone.
